language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
addons:
  postgresql: "9.3"
before_script:
  - psql -U postgres -c 'CREATE EXTENSION IF NOT EXISTS "uuid-ossp";'
script: make test
after_success:
  coveralls
